### ISSUE TITLE
Error: Failed to activate the html-template-generator package

### ISSUE THREAD

**Issue by Ruchi1496** [sahiljain112/html-template-generator#1]
## Description:

**Stack Trace:**
```
Error: Cannot find module 'etch'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\RUCHI\github\html-template-generator\lib\html-template-generator-view.js:15:13)
    at Module._compile (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\RUCHI\github\html-template-generator\lib\html-template-generator.js:7:34)
    at Module._compile (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:766:27)
    at Package.module.exports.Package.activateNow (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:181:16)
    at C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:846:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\RUCHI\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:160:19)
```

**Comment by sahiljain112** [comment]
1) Try reinstalling the package.
2) Use command `apm install html-template-generator`
